let state={course:null,sessions:[],sections:[],employees:[],bookings:[]},selectedDate=null,selectedSession=null,selectedSeat=null;
const params=new URLSearchParams(location.search);
const courseIdentifier=params.get('course')||params.get('id');
let courseId=null;
async function init(){
  try{state=await getCourseFull(courseIdentifier);const c=state.course;courseId=c.id;document.title=c.title+' | SIL Academy';courseTitle.textContent=(c.icon||'🎓')+' '+c.title;courseDescription.textContent=c.description||'';tableTitle.textContent=c.title;employeesList.innerHTML=state.employees.map(x=>`<option value="${esc(x.full_name)}">`).join('');renderDays();renderSpeakers();renderSections();subscribe()}catch(e){console.error(e);document.body.innerHTML='<div class="app-shell"><h1>Դասընթացը չի գտնվել</h1><a href="index.html">Վերադառնալ</a></div>'}}

function renderSpeakers(){
  const rows=(state.speakers||[]).filter(x=>x.is_active!==false);
  if(!rows.length){speakerAside.classList.add('hidden');speakerAside.innerHTML='';return}
  speakerAside.classList.remove('hidden');
  speakerAside.innerHTML=`<div class="speaker-panel glass"><p class="speaker-kicker">${rows.length>1?'SPEAKERS':'SPEAKER'}</p>${rows.map(s=>`<article class="speaker-card">${s.photo_url?`<img src="${esc(s.photo_url)}" alt="${esc(s.full_name)}">`:`<div class="speaker-placeholder">👤</div>`}<div><h3>${esc(s.full_name)}</h3>${s.job_title?`<p class="speaker-role">${esc(s.job_title)}</p>`:''}${s.company?`<p class="speaker-company">${esc(s.company)}</p>`:''}${s.bio?`<p class="speaker-bio">${esc(s.bio)}</p>`:''}</div></article>`).join('')}</div>`;
}

function bookedCount(id){return state.bookings.filter(b=>b.session_id===id).length}
function renderDays(){const dates=[...new Set(state.sessions.map(s=>s.session_date))].sort();daysGrid.innerHTML=dates.map(d=>{const ss=state.sessions.filter(s=>s.session_date===d),free=ss.reduce((a,s)=>a+Math.max(0,s.seats-bookedCount(s.id)),0);return `<button class="choice-card" data-date="${d}"><strong>${formatDate(d)}</strong><span>${ss.length} ժամ</span><div class="free-count">${free} ընդհանուր ազատ տեղ</div></button>`}).join('')||'<div class="empty-state">Դեռ օրեր չկան։</div>'}
function renderSessions(){selectedSession=null;selectedSeat=null;seatSection.classList.add('hidden');const ss=state.sessions.filter(s=>s.session_date===selectedDate);sessionsGrid.innerHTML=ss.map(s=>`<button class="choice-card" data-session="${s.id}"><strong>${esc(s.session_time)}</strong><span>${s.seats} տեղ</span><div class="free-count">${Math.max(0,s.seats-bookedCount(s.id))} ազատ տեղ</div></button>`).join('')}
daysGrid.onclick=e=>{const b=e.target.closest('[data-date]');if(!b)return;selectedDate=b.dataset.date;daysGrid.querySelectorAll('[data-date]').forEach(x=>x.classList.toggle('active',x===b));renderSessions()};
sessionsGrid.onclick=e=>{const b=e.target.closest('[data-session]');if(!b)return;selectedSession=state.sessions.find(s=>s.id===b.dataset.session);sessionsGrid.querySelectorAll('[data-session]').forEach(x=>x.classList.toggle('active',x===b));renderSeats()};
function renderSeats(){seatSection.classList.remove('hidden');seatCountLabel.textContent=selectedSession.seats+' տեղ';seatMap.querySelectorAll('.seat-wrap').forEach(x=>x.remove());const bs=state.bookings.filter(b=>b.session_id===selectedSession.id);for(let i=1;i<=selectedSession.seats;i++){const a=Math.PI*2*(i-1)/selectedSession.seats-Math.PI/2,x=50+42*Math.cos(a),y=50+42*Math.sin(a),bk=bs.find(b=>b.seat_no===i);seatMap.insertAdjacentHTML('beforeend',`<div class="seat-wrap" style="left:${x}%;top:${y}%"><button class="seat ${bk?'booked':''}" data-seat="${i}" ${bk?'disabled':''}><span class="arm left"></span><span class="arm right"></span><span class="num">${i}</span></button>${bk?`<div class="booked-name">${esc(bk.employee_name)}</div>`:''}</div>`)}seatMap.querySelectorAll('.seat:not(.booked)').forEach(b=>b.onclick=()=>{selectedSeat=Number(b.dataset.seat);seatMap.querySelectorAll('.seat').forEach(x=>x.classList.toggle('selected',Number(x.dataset.seat)===selectedSeat));updateSummary()});updateSummary()}
function updateSummary(){bookingSummary.textContent=selectedSession?`${formatDate(selectedSession.session_date)} • ${selectedSession.session_time}${selectedSeat?' • նստատեղ '+selectedSeat:''}`:'Օրը, ժամը և նստատեղը դեռ ընտրված չեն։';bookBtn.disabled=!(employeeInput.value.trim()&&selectedSession&&selectedSeat)}employeeInput.oninput=updateSummary;
bookBtn.onclick=async()=>{const employee=employeeInput.value.trim();if(!employee)return;bookBtn.disabled=true;const {error}=await sb.from('academy_bookings').insert({course_id:courseId,session_id:selectedSession.id,employee_name:employee,seat_no:selectedSeat});if(error){toast(error.code==='23505'?'Այս աշխատակիցը կամ նստատեղն արդեն գրանցված է։':error.message);updateSummary();return}toast('Գրանցումը պահպանվեց։');selectedSeat=null;await refreshBookings()};
async function refreshBookings(){const {data,error}=await sb.from('academy_bookings').select('*').eq('course_id',courseId);if(!error){state.bookings=data||[];renderDays();if(selectedSession)renderSeats()}}
function renderSections(){dynamicSections.innerHTML=state.sections.map(s=>{const cfg=s.content||{};if(s.type==='files'){const files=cfg.files||[];return `<section class="materials-card glass"><div class="materials-head"><div class="materials-icon">📚</div><div><h2>${esc(s.title||'Նյութեր')}</h2><p>${esc(cfg.text||'')}</p></div></div><div class="materials-actions">${files.map(f=>`<a class="material-link" href="${esc(f.url)}" target="_blank">📄 ${esc(f.label||f.name)}</a>`).join('')}</div></section>`}if(s.type==='images'){return `<section class="materials-card glass"><div class="materials-head"><div class="materials-icon">🖼️</div><div><h2>${esc(s.title||'Նկարներ')}</h2></div></div><div class="image-gallery">${(cfg.images||[]).map(f=>`<figure class="image-item"><img src="${esc(f.url)}" alt="${esc(f.label||'Նկար')}"><figcaption>${esc(f.label||'')}</figcaption></figure>`).join('')}</div></section>`}if(s.type==='announcement')return `<section class="announcement"><strong>📢 ${esc(s.title)}</strong><p>${esc(cfg.text||'').replace(/\n/g,'<br>')}</p></section>`;if(s.type==='link')return `<section class="panel glass"><h2>${esc(s.title)}</h2><p>${esc(cfg.text||'')}</p><a class="primary-btn inline" target="_blank" href="${esc(cfg.url||'#')}">${esc(cfg.label||'Բացել')}</a></section>`;if(s.type==='faq')return `<section class="panel glass"><h2>${esc(s.title)}</h2>${(cfg.items||[]).map(i=>`<details class="faq-item"><summary>${esc(i.q)}</summary><p>${esc(i.a)}</p></details>`).join('')}</section>`;return `<section class="panel glass"><h2>${esc(s.title)}</h2><p class="section-content">${esc(cfg.text||'').replace(/\n/g,'<br>')}</p></section>`}).join('')}
function subscribe(){sb.channel('academy-bookings-'+courseId).on('postgres_changes',{event:'*',schema:'public',table:'academy_bookings',filter:`course_id=eq.${courseId}`},refreshBookings).subscribe()}
init();
